#daemon            off;
#worker_processes  auto;
worker_processes  1;

error_log  stderr debug;

pid        /var/log/nginx/nginx.pid;

events {
    worker_connections 2048;
    multi_accept       on;
    accept_mutex       off;
}

pcre_jit    on;
thread_pool default threads=32 max_queue=65536;

http {
    client_body_temp_path       /tmp/nginx_client;
    fastcgi_temp_path           /tmp/fastcgi;
    proxy_temp_path             /tmp/nginx_proxy;
    uwsgi_temp_path             /tmp/uwsgi;
    scgi_temp_path              /tmp/scgi;

    lua_socket_log_errors       off;
    lua_regex_cache_max_entries 40960;

    include            /etc/nginx/mime.types;
    default_type       application/octet-stream;

    log_format         main  '$time_iso8601 [access] "$request" $status $request_time $body_bytes_sent "$http_x_forwarded_for"';

    #log_format         main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                         '$status $body_bytes_sent "$http_referer" '
    #                         '"$http_user_agent" "$http_x_forwarded_for"';

    access_log         /var/log/nginx/access.log  main;

    sendfile           on;
    tcp_nopush         on;

    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;

    keepalive_timeout  65;
    #gzip  on;

    index              index.html index.htm;

    include            /etc/nginx/conf.d/*.conf;

    server_tokens      off;
}
