---
kind: Template
apiVersion: v1
metadata:
  name: "${APP_NAME}-service"
  namespace: ${GROUP_NAME}-${STAGE}
labels:
  template: ${APP_NAME}-service
  app: ${APP_NAME}
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_NAME}
      namespace: ${GROUP_NAME}-${STAGE}
    spec:
      selector:
        app: ${APP_NAME}
      ports:
        - protocol: TCP
          port: 5173
          targetPort: 5173
parameters:
  - name: APP_NAME
  - name: GROUP_NAME
  - name: STAGE