server_names_hash_bucket_size 128;

server {
   listen 80;
   listen [::]:80;
   server_name cms-management-fe-cms-dirty.apps.btpnsdev1.c3vu.p1.openshiftapps.com www.cms-management-fe-cms-dirty.apps.btpnsdev1.c3vu.p1.openshiftapps.com;
   return 301 https://$server_name$request_uri;
}

server {
   client_max_body_size 8M;
   add_header Referrer-Policy "strict-origin-when-cross-origin" always;
   add_header X-Content-Type-Options "nosniff" always;
   add_header X-Frame-Options "SAMEORIGIN" always;
   add_header X-XSS-Protection "1; mode=block" always;

   listen 443 http2 ssl;
   ssl_certificate localhost.crt;        # path to your cacert.pem
   ssl_certificate_key localhost.key;    # path to your privkey.pem

   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   proxy_set_header X-Forwarded-For $remote_addr;
   ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
   ssl_prefer_server_ciphers on;
   ssl_session_cache shared:SSL:10m;

   gzip on;
   gzip_disable "msie6";
   gzip_vary on;
   gzip_proxied any;
   gzip_comp_level 6;
   gzip_buffers 32 4k;
   gzip_http_version 1.1;
   gzip_min_length 20;
   gzip_types text/plain text/css application/javascript  application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype image/svg+xml image/x-icon;
   server_name cms-management-fe-cms-dirty.apps.btpnsdev1.c3vu.p1.openshiftapps.com;
   access_log  logs/cms-management-fe-cms-dirty.apps.btpnsdev1.c3vu.p1.openshiftapps.com.log combined;
   error_log   logs/cms-management-fe-cms-dirty.apps.btpnsdev1.c3vu.p1.openshiftapps.com.error.log error;

    error_page  403 /error/404.html;
    error_page  404 /error/404.html;
    error_page  500 502 503 504 /error/50x.html;

    location ~* "/\.(htaccess|htpasswd)$" {
        deny    all;
        return  404;
    }
    location / {
        proxy_pass http://localhost:5173;
        # root   C:\Users\dyan_w1523\project\mitrais\btpns\miangas\dist;
        # index  index.html index.htm;
        # try_files $uri  /index.html;
    }
    location /api/ {
        tcp_nodelay             on;

        proxy_http_version      1.1;
        proxy_buffering          off;
        proxy_connect_timeout    30s;
        proxy_read_timeout       2m;
        proxy_socket_keepalive   on;
        proxy_next_upstream      off;

        location /api/cms-management {
            rewrite  ^/api/cms-management/(.*) /$1 break;
            proxy_pass https://cms-management-be-cms-dirty.apps.btpnsdev1.c3vu.p1.openshiftapps.com;
        }

    }
}
